name: particle_effect
description: A Flutter package for creating dynamic particle effects with configurable ranges and random movement.
version: 1.0.3
repository: https://github.com/AITripleCodeCorp/particle_effect

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

